---
dependencies:
  - name: "keycloak"
    repository: "https://codecentric.github.io/helm-charts"
    version: "11.0.1"
    condition: "application.activiti-cloud-identity.enabled,activiti-cloud-identity.enabled"
  - name: "kafka"
    repository: "https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami/"
    version: "12.x.x"
    condition: "application.kafka.enabled,kafka.enabled"
  - name: "postgresql"
    repository: "https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami/"
    version: "9.1.1"
    condition: "application.postgresql.enabled,postgresql.enabled"
    alias: "postgresql-headless"
  - name: "common"
    repository: "https://activiti.github.io/activiti-cloud-helm-charts"
    version: "7.8.0-alpha.2"
    condition: "activiti-cloud-modeling.enabled,modeling.enabled"
  - name: "common"
    repository: "https://activiti.github.io/activiti-cloud-helm-charts"
    version: "7.8.0-alpha.2"
    condition: "identity-adapter.enabled,modeling.enabled"
    alias: "cloud-identity-adapter"
  - name: "common"
    repository: "https://activiti.github.io/activiti-cloud-helm-charts"
    version: "7.8.0-alpha.2"
    condition: "activiti-modeling-app.enabled,modeling.enabled"
    alias: "modeling-app"
  - name: "common"
    repository: "https://activiti.github.io/activiti-cloud-helm-charts"
    version: "7.8.0-alpha.2"
    condition: "application.runtime-bundle.enabled,runtime-bundle.enabled"
    alias: "runtime-bundle"
  - name: "common"
    repository: "https://activiti.github.io/activiti-cloud-helm-charts"
    version: "7.8.0-alpha.2"
    condition: "application.activiti-cloud-query.enabled,activiti-cloud-query.enabled"
    alias: "cloud-query"
  - name: "common"
    repository: "https://activiti.github.io/activiti-cloud-helm-charts"
    version: "7.9.0-rc.9"
    condition: "application.activiti-cloud-connector.enabled,activiti-cloud-connector.enabled"
    alias: "cloud-connector"
