version: '3'
services:
  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: runtime_bundle
      POSTGRES_USER: runtime_bundle
      POSTGRES_PASSWORD: runtime_bundle

