global:
  gateway:
    host: host.docker.internal
  keycloak:
    host: host.docker.internal
    clientSecretName: keycloak-client
    useExistingClientSecret: true
  messaging:
    broker: kafka

  postgresql:
    secretName: Murder-Variety-Whoever-Connect-3
    readinessProbeCommand: ["psql", "-w", "-U", "abcd", "-d", "my-db", "-c", "SELECT 1"]
    auth:
      postgresPassword: About-Money-Roll-Blame-5
      erlangCookie: O9yBhb0WeQpEUWad9W4dC3x1QNGGOf9Q
#      existingSecret: glory-sick-page-bear-9-i
      database: core-bpmn
postgresql:
  readinessProbeCommand: ["psql", "-w", "-U", "abcd", "-d", "my-db", "-c", "SELECT 1"]
keycloak:
  auth:
    adminPassword: About-Money-Roll-Blame-5
