global:
  gateway:
    host: host.docker.internal
  keycloak:
    host: host.docker.internal
    clientSecretName: activiti-keycloak-client
    useExistingClientSecret: true
  messaging:
    broker: kafka

kafka:
  enabled: true
rabbitmq:
  enabled: false
