global:
  gateway:
    host: host.docker.internal
  keycloak:
    host: host.docker.internal
    clientSecretName: keycloak-client
    useExistingClientSecret: true
  messaging:
    broker: kafka
  postgresql:
    secretName: boogersnot
#    readinessProbeCommand: ["psql", "-w", "-U", "abcd", "-d", "my-db", "-c", "SELECT 1"]
    readinessProbe:
      exec:
        command: [ "psql", "-w", "-U", "abcd", "-d", "my-db", "-c", "SELECT 1" ]
      initialDelaySeconds: 15
    auth:
      username: admin
      password: YCKl4kX8x2
      erlangCookie: O9yBhb0WeQpEUWad9W4dC3x1QNGGOf9Q
      existingSecret: thisisasecret
      database: core-bpmn
postgresql:

    timeoutSeconds: 2
